### ISSUE TITLE
Fail To Run In Android 6,7

### ISSUE THREAD

**Issue by nemesis567** [Shin-NiL/Godot-Share#9] opened 2019-07-23 06:31 UTC
Godot version:
3.1-stable

OS/device including version:
Android 6, 7
Compiled on Windows 10

Issue description:
ATAL EXCEPTION: GLThread 557 Process: com.murderintheshadows.aelia, PID: 9604 java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotShare" on path: DexPathList[[zip file "/data/app/com.murderintheshadows.aelia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.murderintheshadows.aelia-1/lib/arm64, /data/app/com.murderintheshadows.aelia-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:380) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at org.godotengine.godot.GodotLib.setup(Native Method) at org.godotengine.godot.Godot$2.run(Godot.java:311) at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1481) at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253) Suppressed: java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotFacebook" on path: DexPathList[[zip file "/data/app/com.murderintheshadows.aelia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.murderintheshadows.aelia-1/lib/arm64, /data/app/com.murderintheshadows.aelia-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]] ... 7 more

Steps to reproduce:
You can download the project, compile, export and try to run on android 6, app crashes with error above.
This runs fine on Android 8+

**Comment by Shin-NiL** [comment] 2019-07-23 12:00
> Didn't find class "org/godotengine/godot/GodotShare"

That's the issue, double check if the custom template is set on the Android export options (debug & release). If you have compiled the template, something must be wrong there too.

**Comment by nemesis567** [comment] 2019-07-23 18:44
It is set, like I said this works properly on android 8+, just doesn't work on 6 and 7.

**Comment by Shin-NiL** [comment] 2019-07-23 18:49
I only have Android 7 and it's working fine too. Does the app work without this module?

**Comment by nemesis567** [comment] 2019-07-23 19:02
Yes, it does.

**Comment by nemesis567** [comment] 2019-07-23 19:04
![screencapture-play-google-apps-publish-2019-07-23-20_02_18](https://user-images.githubusercontent.com/5153909/61739761-0228e180-ad85-11e9-89ad-64126c224ae5.png)

**Comment by Shin-NiL** [comment] 2019-07-24 11:08
Are you compiling the templates or using precompiled ones? It looks like the module was not found in the template file (arm64). I have no Idea what could be the cause.

**Comment by nemesis567** [comment] 2019-07-24 15:28
I've fixed this by cleaning the solution, rebuilding and for release build using ./gradlew assembleRelease instead of build. Changing the project name and full path to both sdk and engine to not contain spaces assisted with being able to build with assembleRelease. It was also important to add Android 6 and 7 SDKs to the android SDK, despite godot saying it loads the necessary dependencies automatically, I don't think it was happening.

**Comment by Shin-NiL** [comment] 2019-07-24 16:33
Alright, I'll close the issue as it seems not to be an error of this module.

**Closed as completed by Shin-NiL** 2019-07-24 16:33 UTC
